
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import store from './StoreProvider'
import { Provider } from 'react-redux'
import { AuthProvider } from './provider'
import StoreProvider from './StoreProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <AuthProvider>
          <StoreProvider>
              <Navbar />
              <div className='home'>
              {children}
              </div>
              <Footer/>
        </StoreProvider>
        </AuthProvider>
        
        </body>
    </html>
  )
}
